name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - development-5

defaults:
  run:
    shell: bash

env:
  RUBY_VERSION: 2.6.6
  NODE_VERSION: 14.20.0
  BUNDLER_VERSION: 1.17.3

jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      image: jancbrammer/complat-ubuntu-runner:development-5    # TODO: serve image from complat account
      env:
        ImageOS: ubuntu20    # OS of the container image; required by ruby/setup-ruby@v1

    services:
      postgres:
        image: postgres    # https://hub.docker.com/_/postgres
        env:
          POSTGRES_PASSWORD: postgres    # env variable required by postgres Docker container
          POSTGRES_USER: chemotion    # optional env variable used in conjunction with POSTGRES_PASSWORD to set a user and their password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: configure repository
        run: |
          mv public/welcome-message-sample.md public/welcome-message.md
          cd config
          cp database.yml.gitlab database.yml
          cp -f storage.yml.example storage.yml
          touch datacollectors.yml
          cp -f profile_default.yml.example profile_default.yml
          touch klasses.json

      - name: configure postgres
        env:
          PG_ROLE: chemotion_test
          PG_ROLE_PASSWORD: 123456
          PG_DATABASE: chemotion_test
          PGPASSWORD: postgres    # env variable required by psql client
        run: |    # host is service container name
            psql -h postgres -U chemotion -c "CREATE ROLE $PG_ROLE LOGIN CREATEDB NOSUPERUSER PASSWORD '$PG_ROLE_PASSWORD';"
            psql -h postgres -U chemotion -c "CREATE DATABASE $PG_DATABASE OWNER $PG_ROLE;"
            psql -d postgresql://$PG_ROLE:$PG_ROLE_PASSWORD@postgres/$PG_DATABASE -c 'CREATE EXTENSION IF NOT EXISTS "pg_trgm"; CREATE EXTENSION IF NOT EXISTS "hstore"; CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'

      - name: bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler: ${{ env.BUNDLER_VERSION }}
          bundler-cache: true    # runs 'bundle install' and caches installed gems automatically (cache based on hash of Gemfile.lock)

      - name: setup nodejs and npm cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: setup yarn    # TODO: keep an eye on https://github.com/actions/setup-node/issues/182 to potentially remove this, and the next two steps
        run: npm install -g yarn

      - name: setup yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: yarn install
        run: yarn install --frozen-lockfile --prefer-offline    # --frozen-lockfile: don't generate yarn.lock, --prefer-offline: use cache

      - name: prepare postgres
        run: |
          RAILS_ENV=test bundle exec rake db:migrate
          RAILS_ENV=test bundle exec rake db:test:prepare
          RAILS_ENV=test bundle exec rake db:seed

      - name: precompile
        run: RAILS_ENV=test bundle exec rake webpacker:compile

      - name: npm test
        run: npm test

      - name: rspec acceptance
        run: RAILS_ENV=test bundle exec rspec spec/features

      - name: rspec unit
        run: RAILS_ENV=test bundle exec rspec --exclude-pattern spec/{features}/**/*_spec.rb

      - name: coverage rspec unit
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov/chemotion_ELN.lcov
          minimum-coverage: 50
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
